### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by shivaang12** [u1234x1234/pyvlfeat#1]
I am getting below error when installing through `python setup.py install`

```
vlfeat/py_vlfeat.cpp:78:2: error: void function 'init_module__vlfeat' should not return a value [-Wreturn-type]
        import_array();
        ^~~~~~~~~~~~~~
/Users/shivang/pyenvs/pytorch/lib/python3.8/site-packages/numpy/core/include/numpy/__multiarray_api.h:1531:144: note: expanded from
      macro 'import_array'
  ...< 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NULL; } }
                                                                                                        ^      ~~~~
1 error generated.
error: command 'gcc' failed with exit status 1
```

It would be really helpful if you can help.
Thanks!

P.S I am using OSX Catalina

**Comment by u1234x1234** [comment]
Hello Shivang,

Sorry, but I wasn't able to reproduce the error, as I have no OSX at hand.
I've tried to build in a linux environment and everything went smoothly, check out the [Dockerfile for the reference](https://github.com/u1234x1234/pyvlfeat/blob/master/Dockerfile).

I guess the error stems from the combination of Python version / gcc / boost-python, as the code is kinda dated. You could try to lower the python version, or modify the source code by removing the following line:
https://github.com/u1234x1234/pyvlfeat/blob/master/vlfeat/py_vlfeat.cpp#L78

**Comment by shivaang12** [comment]
Thanks for the help. Lets just say OSX has many problems. Linux it is then.
